/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsCreateRouteImport } from './routes/groups/create'
import { Route as GroupsIdRouteImport } from './routes/groups/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as GroupsIdRequestsRouteImport } from './routes/groups/$id.requests'
import { Route as GroupsIdFilesRouteImport } from './routes/groups/$id.files'
import { Route as GroupsIdEditRouteImport } from './routes/groups/$id.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRequestsRoute = GroupsIdRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => GroupsIdRoute,
} as any)
const GroupsIdFilesRoute = GroupsIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => GroupsIdRoute,
} as any)
const GroupsIdEditRoute = GroupsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GroupsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/groups/$id': typeof GroupsIdRouteWithChildren
  '/groups/create': typeof GroupsCreateRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$id/edit': typeof GroupsIdEditRoute
  '/groups/$id/files': typeof GroupsIdFilesRoute
  '/groups/$id/requests': typeof GroupsIdRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/groups/$id': typeof GroupsIdRouteWithChildren
  '/groups/create': typeof GroupsCreateRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$id/edit': typeof GroupsIdEditRoute
  '/groups/$id/files': typeof GroupsIdFilesRoute
  '/groups/$id/requests': typeof GroupsIdRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/groups/$id': typeof GroupsIdRouteWithChildren
  '/groups/create': typeof GroupsCreateRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$id/edit': typeof GroupsIdEditRoute
  '/groups/$id/files': typeof GroupsIdFilesRoute
  '/groups/$id/requests': typeof GroupsIdRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/groups/$id'
    | '/groups/create'
    | '/groups'
    | '/groups/$id/edit'
    | '/groups/$id/files'
    | '/groups/$id/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/groups/$id'
    | '/groups/create'
    | '/groups'
    | '/groups/$id/edit'
    | '/groups/$id/files'
    | '/groups/$id/requests'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/groups/$id'
    | '/groups/create'
    | '/groups/'
    | '/groups/$id/edit'
    | '/groups/$id/files'
    | '/groups/$id/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  GroupsIdRoute: typeof GroupsIdRouteWithChildren
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/requests': {
      id: '/groups/$id/requests'
      path: '/requests'
      fullPath: '/groups/$id/requests'
      preLoaderRoute: typeof GroupsIdRequestsRouteImport
      parentRoute: typeof GroupsIdRoute
    }
    '/groups/$id/files': {
      id: '/groups/$id/files'
      path: '/files'
      fullPath: '/groups/$id/files'
      preLoaderRoute: typeof GroupsIdFilesRouteImport
      parentRoute: typeof GroupsIdRoute
    }
    '/groups/$id/edit': {
      id: '/groups/$id/edit'
      path: '/edit'
      fullPath: '/groups/$id/edit'
      preLoaderRoute: typeof GroupsIdEditRouteImport
      parentRoute: typeof GroupsIdRoute
    }
  }
}

interface GroupsIdRouteChildren {
  GroupsIdEditRoute: typeof GroupsIdEditRoute
  GroupsIdFilesRoute: typeof GroupsIdFilesRoute
  GroupsIdRequestsRoute: typeof GroupsIdRequestsRoute
}

const GroupsIdRouteChildren: GroupsIdRouteChildren = {
  GroupsIdEditRoute: GroupsIdEditRoute,
  GroupsIdFilesRoute: GroupsIdFilesRoute,
  GroupsIdRequestsRoute: GroupsIdRequestsRoute,
}

const GroupsIdRouteWithChildren = GroupsIdRoute._addFileChildren(
  GroupsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  GroupsIdRoute: GroupsIdRouteWithChildren,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
